//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.15 at 09:40:27 AM CET 
//


package it.smartcommunitylab.trentorienta.soapservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.smartcommunitylab.trentorienta.soapservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResponseList_QNAME = new QName("http://smartcommunitylab.it/trentorienta/soapservice", "responseList");
    private final static QName _TagResponseList_QNAME = new QName("http://smartcommunitylab.it/trentorienta/soapservice", "tagResponseList");
    private final static QName _ThemeResponseList_QNAME = new QName("http://smartcommunitylab.it/trentorienta/soapservice", "themeResponseList");
    private final static QName _EventType_QNAME = new QName("http://smartcommunitylab.it/trentorienta/soapservice", "eventType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.smartcommunitylab.trentorienta.soapservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link RequestList }
     * 
     */
    public RequestList createRequestList() {
        return new RequestList();
    }

    /**
     * Create an instance of {@link TagRequestList }
     * 
     */
    public TagRequestList createTagRequestList() {
        return new TagRequestList();
    }

    /**
     * Create an instance of {@link ThemeRequestList }
     * 
     */
    public ThemeRequestList createThemeRequestList() {
        return new ThemeRequestList();
    }

    /**
     * Create an instance of {@link EventRequest }
     * 
     */
    public EventRequest createEventRequest() {
        return new EventRequest();
    }

    /**
     * Create an instance of {@link SearchRequest }
     * 
     */
    public SearchRequest createSearchRequest() {
        return new SearchRequest();
    }

    /**
     * Create an instance of {@link EventTypeList }
     * 
     */
    public EventTypeList createEventTypeList() {
        return new EventTypeList();
    }

    /**
     * Create an instance of {@link Greeting }
     * 
     */
    public Greeting createGreeting() {
        return new Greeting();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smartcommunitylab.it/trentorienta/soapservice", name = "responseList")
    public JAXBElement<Object> createResponseList(Object value) {
        return new JAXBElement<Object>(_ResponseList_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smartcommunitylab.it/trentorienta/soapservice", name = "tagResponseList")
    public JAXBElement<Object> createTagResponseList(Object value) {
        return new JAXBElement<Object>(_TagResponseList_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smartcommunitylab.it/trentorienta/soapservice", name = "themeResponseList")
    public JAXBElement<Object> createThemeResponseList(Object value) {
        return new JAXBElement<Object>(_ThemeResponseList_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smartcommunitylab.it/trentorienta/soapservice", name = "eventType")
    public JAXBElement<Object> createEventType(Object value) {
        return new JAXBElement<Object>(_EventType_QNAME, Object.class, null, value);
    }

}
